services:
  db:                              # This is the name of our service
    image: postgres:18     # Download PostgreSQL 18 Debian 
    container_name: quotes_db      # A friendly name for the container
    restart: always                # Auto-restart if the container crashes
    environment:
      POSTGRES_USER: quotesuser    # The database username
      POSTGRES_PASSWORD: quotespass  # The database password
      POSTGRES_DB: quotesdb        # The name of the database to create
    ports:
      - '5432:5432'               # Connect port 5432 on your Mac to port 5432 in Docker
    volumes:
      - quotes_data:/var/lib/postgresql  # Save data permanently

volumes:
  quotes_data:                     # Defines the permanent storage volume